### ISSUE TITLE
CardMedia is being hydrated as div, instead of img (Image not being rendered)

### ISSUE THREAD

**Issue by vinaybedre** [swordev/suid#174]
A sample repo is here https://stackblitz.com/edit/angular-id8ttt?file=src%2FApp.tsx

I am using suid's CardMedia to render an image, but its being rendered as `div` instead of `img` tag and hence I cannot see the image at all

```typescript
    <Card sx={{ maxWidth: 345 }}>
      <CardMedia
        sx={{ height: 140 }}
        image="https://via.placeholder.com/150"
        title="green iguana"
      />
    </Card>
```

**Comment by juanrgm** [comment]
It was fixed at [@suid/material@0.10.0](https://github.com/swordev/suid/releases/tag/%40suid%2Fmaterial%400.10.0).

**Comment by vinaybedre** [comment]
@juanrgm 
I can see its still happening with V0.10.0, see the stackblitz link above.
![Screenshot 2023-02-02 at 9 35 43 PM](https://user-images.githubusercontent.com/2630384/216443897-66e39a76-fb74-4b59-a003-f5608d6f2f9e.png)
![Screenshot 2023-02-02 at 9 35 36 PM](https://user-images.githubusercontent.com/2630384/216443901-6851e6d5-db2b-4930-878c-05a279689548.png)

**Comment by juanrgm** [comment]
Closed via 28f1bda4502591fe6da237e3215cb4fdb846daa6.
